### ISSUE TITLE
test 2

### ISSUE THREAD

**Issue by OldJERN8322** [Maxi2022gt/anychatinissuesordiscussions#2]
hi

**Comment by Maxi2022gt** [comment]
oh hi

**Comment by Maxi2022gt** [comment]
helo

**Comment by OldJERN8322** [comment]
Also i called on peoplearecool1234. ausdfgs

![image](https://user-images.githubusercontent.com/99561059/187571024-46e3628a-3819-4f4b-8940-b002cb7dc1de.png)

**Comment by Maxi2022gt** [comment]
ok
i have discord but i cant message to anyone
only to my brother

**Comment by OldJERN8322** [comment]
f

**Comment by Maxi2022gt** [comment]
yep, i wish if i cloud message to anyone but i cant

**Comment by Maxi2022gt** [comment]
yep

**Comment by OldJERN8322** [comment]
ololo

**Comment by Maxi2022gt** [comment]
elellelelellellelñlktgfuio8dckdgjuijkg65iu8gyig77896utygierutgghhghfggv
![image](https://user-images.githubusercontent.com/106933671/187571537-299c62a3-b92d-4e91-af62-d7a7ecec0c06.png)sdafdsjhguyyigbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgg
![image](https://user-images.githubusercontent.com/106933671/187571537-299c62a3-b92d-4e91-af62-d7a7ecec0c06.png)afdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsdsgdsfds
jukilbvkuilfdvfbgopñkhbbvh,gvdf

**Comment by OldJERN8322** [comment]
wt

**Comment by Maxi2022gt** [comment]
idk

**Comment by Maxi2022gt** [comment]
what happened

**Comment by Maxi2022gt** [comment]
![image](https://user-images.githubusercontent.com/106933671/187571873-03cb273c-8b12-4389-b4e9-1513751a1f6d.png)
![image](https://user-images.githubusercontent.com/106933671/187571874-d120f408-a7d9-4b47-9b4c-067729bec889.png)
![image](https://user-images.githubusercontent.com/106933671/187571875-2109bd9a-401b-4fa0-92b9-c793e6e3f4ca.png)
![image](https://user-images.githubusercontent.com/106933671/187571878-607ee4af-70cc-4872-96b1-8c2a31c1788e.png)
![image](https://user-images.githubusercontent.com/106933671/187571876-bc97d3d6-cf3b-40be-b17c-cf422ebad410.png)
![image](https://user-images.githubusercontent.com/106933671/187571877-9ccc336a-61ab-4f88-a829-6866f0b4cc2b.png)
![image](https://user-images.githubusercontent.com/106933671/187571879-d489e8ee-99b4-4e33-9c45-0a4348f3bf76.png)
![image](https://user-images.githubusercontent.com/106933671/187571880-cc211f41-f758-4c55-a60f-7c34a3684112.png)
![image](https://user-images.githubusercontent.com/106933671/187571881-53e93ba0-2f80-4459-b2e3-6b6dd4290e8a.png)
![image](https://user-images.githubusercontent.com/106933671/187571884-cc853f5d-4376-4629-b80c-32b91240761b.png)
![image](https://user-images.githubusercontent.com/106933671/187571882-199468b6-51ad-4ed7-9f83-fcc50505c6d5.png)

**Comment by OldJERN8322** [comment]
AIRARRIRAIRRRIRARAIRAIRARAirovfywejvturjuyt54jgr

**Comment by OldJERN8322** [comment]
air moments

**Comment by OldJERN8322** [comment]
** **

**Comment by Maxi2022gt** [comment]
lel

**Comment by Maxi2022gt** [comment]
>

**Comment by OldJERN8322** [comment]
👁👄👁

**Comment by Maxi2022gt** [comment]
wth

**Comment by Maxi2022gt** [comment]
perfect timing sdfjguikyjvgf

**Comment by Maxi2022gt** [comment]
- fhdg hfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfgfghgdffgsadfasdf`safadsfsacsfasdfsaf`

**Comment by OldJERN8322** [comment]
wtf

**Comment by OldJERN8322** [comment]
wait. i changed icons.

**Comment by Maxi2022gt** [comment]
yep

**Comment by Maxi2022gt** [comment]
> 

> 

>

**Comment by OldJERN8322** [comment]
Done

**Comment by Maxi2022gt** [comment]
woah cool

**Comment by OldJERN8322** [comment]
Thanks

**Comment by OldJERN8322** [comment]
Holy 9 more comments

**Comment by Maxi2022gt** [comment]
also i want to change my yt icon too jkuloip98f7ugcf89odg

**Comment by Maxi2022gt** [comment]
8 more comments to?

**Comment by OldJERN8322** [comment]
6 MORE COMMENTS AAAAAAAAA

**Comment by Maxi2022gt** [comment]
TO 50 COMMENTS?

**Comment by OldJERN8322** [comment]
YES

**Comment by OldJERN8322** [comment]
3

**Comment by OldJERN8322** [comment]
2

**Comment by Maxi2022gt** [comment]
"pullbar"
![image](https://user-images.githubusercontent.com/106933671/187572754-cd7514da-4e9c-46c7-8fba-c6ffb945589e.png)

**Comment by OldJERN8322** [comment]
50 COMMENTS!!!

**Comment by Maxi2022gt** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by Maxi2022gt** [comment]
idk what to say

**Comment by OldJERN8322** [comment]
HOLY SPAM KEYBOARD

**Comment by Maxi2022gt** [comment]
yes

**Comment by Maxi2022gt** [comment]
![image](https://user-images.githubusercontent.com/106933671/187572987-08324af5-5157-45e9-8e41-8f70fe213b2a.png)
![image](https://user-images.githubusercontent.com/106933671/187573016-aaba59de-d22f-40ef-b464-237580849cb1.png)
tomb forgetted to change his pfp in his second account

**Comment by Maxi2022gt** [comment]
yep

**Comment by Maxi2022gt** [comment]
also almost dead chat

**Comment by OldJERN8322** [comment]
askgdad

**Comment by OldJERN8322** [comment]
8

**Comment by OldJERN8322** [comment]
6

**Comment by OldJERN8322** [comment]
5

**Comment by OldJERN8322** [comment]
4

**Comment by OldJERN8322** [comment]
3

**Comment by OldJERN8322** [comment]
2

**Comment by OldJERN8322** [comment]
1

**Comment by OldJERN8322** [comment]
6969699696969rfwytvwhfvyu2ftyvehgcuxwygfcwgeh

**Comment by Maxi2022gt** [comment]
69

**Comment by OldJERN8322** [comment]
BRUH I MISSING AAAAA

**Comment by Maxi2022gt** [comment]
uip9oghldo9pvfg`ghdfghdghdgfhfghfdhdhfg`fhdghdfghdfhdfghdfg`dfghdfghfgdhfd`hdgfgfdhfhgddddddddddddd

> ### **fhdggfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhdfhd_dfhgggggggggggggggggggggggghdfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff_**

**Comment by OldJERN8322** [comment]
wtf

**Comment by Maxi2022gt** [comment]
idk

**Comment by OldJERN8322** [comment]
`69 moments`

**Comment by Maxi2022gt** [comment]
>

**Comment by OldJERN8322** [comment]
wtsdfhgudf

**Comment by Maxi2022gt** [comment]
> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> @

**Comment by Maxi2022gt** [comment]
also e

**Comment by Maxi2022gt** [comment]
![image](https://user-images.githubusercontent.com/106933671/187574304-587be6a9-c64d-49ce-aa39-8342c908833c.png)
F

**Comment by OldJERN8322** [comment]
f moments lmao

**Comment by OldJERN8322** [comment]
ñoñeññoñ

**Comment by Maxi2022gt** [comment]
lamo

**Comment by OldJERN8322** [comment]
![image](https://user-images.githubusercontent.com/99561059/187574848-759854dd-66b6-49a3-ad82-7053d3cabd99.png)
test

**Comment by OldJERN8322** [comment]
test 2
![image](https://user-images.githubusercontent.com/99561059/187574867-bd1464b4-5afb-4dea-b33f-9499e327d834.png)

**Comment by OldJERN8322** [comment]
test 3
![image](https://user-images.githubusercontent.com/99561059/187574886-b18fe8a2-3adc-4a78-a942-513b48c9cec9.png)

**Comment by Maxi2022gt** [comment]
lamoi

**Comment by OldJERN8322** [comment]
9 MORE FOR 100 COMMENTS

**Comment by Maxi2022gt** [comment]
stop fjhfyiud8cahs7jgkfe

**Comment by OldJERN8322** [comment]
5 MORE

**Comment by Maxi2022gt** [comment]
YESSSSSSSSSSSSSSSSSSSSSSSS

**Comment by OldJERN8322** [comment]
4 MORE AAAAAA

**Comment by OldJERN8322** [comment]
THREE

**Comment by OldJERN8322** [comment]
TWO

**Comment by Maxi2022gt** [comment]
![Uploading image.png…]()
test 6

**Comment by OldJERN8322** [comment]
100 COMMENTS YAAAAAAAAAAAAAAAAY!!!!!!!!!!!!

**Comment by Maxi2022gt** [comment]
qewradswrfs

**Comment by OldJERN8322** [comment]
qwerty

**Comment by Maxi2022gt** [comment]
elrel

**Comment by OldJERN8322** [comment]
ñ el ñaña

**Comment by OldJERN8322** [comment]
asfdvgwefhfgkj

**Comment by Maxi2022gt** [comment]
test 7
![image](https://user-images.githubusercontent.com/106933671/187575314-16d538ed-2253-49db-bbe0-67fe1657f169.png)

**Comment by Maxi2022gt** [comment]
ell

**Comment by OldJERN8322** [comment]
ñ

**Comment by OldJERN8322** [comment]
AAAAAASJMVHGWHYUG$YUVUTUWHJHFUNSCDGCU#HY

**Comment by OldJERN8322** [comment]
![image](https://user-images.githubusercontent.com/99561059/187575504-2658fa6c-4433-4604-8a79-8badd993198d.png)
WELL THAT FOUND IT FUN AKLGJYHJUGVFRE

**Comment by Maxi2022gt** [comment]
hi

**Comment by OldJERN8322** [comment]
ihi

**Comment by Maxi2022gt** [comment]
sorry

**Comment by OldJERN8322** [comment]
AAAAAAAAAA HELP ME 😂

**Comment by Maxi2022gt** [comment]
elellelñr

**Comment by OldJERN8322** [comment]
also. i'm bored

**Comment by Maxi2022gt** [comment]
mee too

**Comment by OldJERN8322** [comment]
lol

**Comment by Maxi2022gt** [comment]
also i want to learn how to make a os like yours upolskifcdo

**Comment by Maxi2022gt** [comment]
how do i make a os like yours jyu7

**Comment by Maxi2022gt** [comment]
![image](https://user-images.githubusercontent.com/106933671/187577322-fb9cc46c-0112-4e64-83d2-7cda7036ee64.png)
also i founded this on joshua's yt

**Comment by OldJERN8322** [comment]
wow

**Comment by OldJERN8322** [comment]
also. mom is sleeping

**Comment by Maxi2022gt** [comment]
yep

**Comment by Maxi2022gt** [comment]
how do i make a os in powerpoint

**Comment by OldJERN8322** [comment]
also.
https://www.youtube.com/results?search_query=how+to+make+os+powerpoint

**Comment by Maxi2022gt** [comment]
i learn with the channel "Project: PowerPoint" idk if it will get good

**Comment by Maxi2022gt** [comment]
if you want i send the os im making with that tutorial

**Comment by OldJERN8322** [comment]
idk. i'm bored this

**Comment by Maxi2022gt** [comment]
me too im bored

**Comment by OldJERN8322** [comment]
`#ffff00` test

**Comment by Maxi2022gt** [comment]
i use powerpoint 2016

**Comment by OldJERN8322** [comment]
okay.

**Comment by Maxi2022gt** [comment]
i have to go bye

**Comment by OldJERN8322** [comment]
Good night.

**Comment by Maxi2022gt** [comment]
i can reopen this lmao

**Comment by Maxi2022gt** [comment]
`#ff0000`
`#690000`

**Comment by Maxi2022gt** [comment]
welp i think jern is offline so ill close

**Comment by Maxi2022gt** [comment]
fish
